{"uuid": "6f05d711-9473-4eae-9fa5-7902f06c6c71", "children": ["d6e7681f-09a2-4d5a-a9bb-983682e6bd84"], "befores": [{"name": "read_base_url", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\PycharmProjects\\\\api_frame\\\\testcases\\\\product_manage\\\\config.yaml'\n", "trace": "  File \"E:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"E:\\PycharmProjects\\api_frame\\testcases\\product_manage\\conftest.py\", line 13, in read_base_url\n    base_product_url = read_config_yaml(\"base\",\"base_product_url\")\n  File \"E:\\PycharmProjects\\api_frame\\commons\\yaml_util.py\", line 30, in read_config_yaml\n    with open(get_object_path()+r\"\\config.yaml\",mode='r',encoding='utf-8') as f:\n"}, "start": 1649997248065, "stop": 1649997248065}], "start": 1649997248065, "stop": 1649997248293}