{"name": "test_get_token", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\PycharmProjects\\\\api_frame\\\\testcases\\\\product_manage\\\\config.yaml'", "trace": "@pytest.fixture(scope=\"function\")\n    def read_base_url():\n>       base_product_url = read_config_yaml(\"base\",\"base_product_url\")\n\nconftest.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\none_node = 'base', tow_node = 'base_product_url'\n\n    def read_config_yaml(one_node,tow_node):\n>       with open(get_object_path()+r\"\\config.yaml\",mode='r',encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\PycharmProjects\\\\api_frame\\\\testcases\\\\product_manage\\\\config.yaml'\n\n..\\..\\commons\\yaml_util.py:30: FileNotFoundError"}, "start": 1649997248062, "stop": 1649997248062, "uuid": "d6e7681f-09a2-4d5a-a9bb-983682e6bd84", "historyId": "29c2ddc2b8139210eaec378da8430f98", "testCaseId": "9e3183cfc5a1216ab764ddb8bcf0e9a9", "fullName": "testcases.product_manage.test_product_api.TestProductApi#test_get_token", "labels": [{"name": "parentSuite", "value": "testcases.product_manage"}, {"name": "suite", "value": "test_product_api"}, {"name": "subSuite", "value": "TestProductApi"}, {"name": "host", "value": "DESKTOP-9RP3D4Q"}, {"name": "thread", "value": "4016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.product_manage.test_product_api"}]}